dist: bionic
sudo: false
language: php

cache:
  directories:
    - $HOME/.composer/cache/files

php:
  - 7.4
  - 7.3
  - 7.2
  - 7.1

env:
  matrix:
    - Laravel=6.0.*
    - Laravel=5.8.*
    - Laravel=5.7.*
    - Laravel=5.6.*
    - Laravel=dev-master

matrix:
  exclude:
    - php: 7.1
      env: Laravel=6.0.*
    - php: 7.1
      env: Laravel=dev-master
  allow_failures:
    - env: Laravel=dev-master
  fast_finish: true

install:
  - travis_retry composer require --dev "laravel/framework:${Laravel}" --no-interaction

script:
  - vendor/bin/phpunit --coverage-clover build/logs/clover.xml

after_success:
  - travis_retry php vendor/bin/coveralls -v
