dist: trusty
sudo: false
language: php

cache:
  directories:
    - $HOME/.composer/cache/files

php:
  - 7.3
  - 7.2
  - 7.1
  - 7.4snapshot # https://travis-ci.community/t/add-php-7-4-branch-to-test-against/2179

env:
  matrix:
    - Laravel=5.8.*
    - Laravel=5.7.*
    - Laravel=5.6.*
    - Laravel=6.0.x-dev

matrix:
  allow_failures:
    - php: 7.4snapshot
    - env: Laravel=6.0.x-dev
  fast_finish: true

install:
  - travis_retry composer require --dev "laravel/framework:${Laravel}" --no-interaction

script:
  - vendor/bin/phpunit --coverage-clover build/logs/clover.xml

after_success:
  - travis_retry php vendor/bin/coveralls -v
