version: '2'

services:

  api-docs:
    image: halverneus/static-file-server
    ports:
      - '8001:8080'
    volumes:
      - ./api-docs:/web

  composer:
    image: composer
    user: $UID:$GID
    volumes:
      - .:/app
      # Composer won't allow a symlink to ".." so map "/breadcrumbs" to the same directory
      - .:/breadcrumbs
      - ./tmp:/tmp

  phpdoc:
    build: ./docker/phpdoc
    user: $UID:$GID
    volumes:
      - .:/app

  phpunit-71:
    build: ./docker/phpunit-71
    user: $UID:$GID
    volumes:
      - .:/app

  phpunit-72:
    build: ./docker/phpunit-72
    user: $UID:$GID
    volumes:
      - .:/app

  readme:
    build: ./docker/grip
    command: grip /app/README.md 0.0.0.0:8000
    user: $UID:$GID
    ports:
      - '8000:8000'
    volumes:
      - .:/app
      - ./tmp/grip:/.grip

  test-app-71:
    image: php:7.1
    command: php -S 0.0.0.0:8071 /app/test-app/public/index.php
    user: $UID:$GID
    ports:
      - '8071:8071'
    volumes:
      - .:/app
      - .:/breadcrumbs

  test-app-72:
    image: php:7.2
    command: php -S 0.0.0.0:8072 /app/test-app/public/index.php
    user: $UID:$GID
    ports:
      - '8072:8072'
    volumes:
      - .:/app
      - .:/breadcrumbs

  test-coverage:
    image: halverneus/static-file-server
    ports:
      - '8002:8080'
    volumes:
      - ./test-coverage:/web
